/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ContratoControlador;
import exepciones.StorageBoxException;
import java.time.LocalDate;
import modelo.Cliente;
import modelo.Contrato;
import modelo.Espacio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author matam
 */
public class FrmContratos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmContratos.class.getName());
    private ContratoControlador controlador;
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form FrmContratos
     */
    public FrmContratos() {
        initComponents();
        configurarTabla();
        setLocationRelativeTo(null);
    }

    public FrmContratos(ContratoControlador controlador) {
        
        initComponents();
        this.controlador = controlador;
        configurarTabla();
        cargarClientes();
        cargarEspacios();
        cargarTablaContratos();
        setLocationRelativeTo(null);
    }
    private void configurarTabla() {

    String[] columnas = {
        "Número Contrato",
        "Cliente",
        "Espacio",
        "Fecha Inicio",
        "Fecha Final",
        "Estado"
    };

    modeloTabla = new DefaultTableModel(columnas, 0);

    tblContratos.setModel(modeloTabla);
    }
    
    private void cargarClientes() {

    cbxCliente.removeAllItems();

    for (Cliente cliente : controlador.listarClientes()) {
        cbxCliente.addItem(cliente.getIdentificacion()+ " - "+ cliente.getNombreCompleto());
        }
    }
    private void cargarEspacios() {

    cbxEspacio.removeAllItems();

    for (Espacio espacio :
            controlador.listarEspaciosDisponibles()) {

        cbxEspacio.addItem(espacio.getNumeroEspacio()+ " - "+ espacio.getTipo());
        }
    } 
    private void cargarTablaContratos() {

    modeloTabla.setRowCount(0);

    for (Contrato contrato :
            controlador.listarContratos()) {

        Object[] fila = {
            contrato.getNumeroContrato(),
            contrato.getCliente().getNombreCompleto(),
            contrato.getEspacio().getNumeroEspacio(),
            contrato.getFechaInicio(),
            contrato.getFechaFinal(),
            contrato.getEstado()
        };

        modeloTabla.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        cbxEspacio = new javax.swing.JComboBox<>();
        txtFechaInicio = new javax.swing.JTextField();
        txtMeses = new javax.swing.JTextField();
        btnEncola = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnProcesar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Gestión de Contratos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Solicitud de Alquiler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cedula y Cliente:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Disponibilidad de Espacios:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Fecha Inicio:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Meses de Alquiler:");

        cbxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101110222 - Juan Pérez", "202220333 - María López", "303330444 - Carlos Ruiz" }));
        cbxCliente.addActionListener(this::cbxClienteActionPerformed);

        cbxEspacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESP-01 - Pequeño (Disponible)", "ESP-02 - Mediano (Disponible)", "ESP-03 - Grande (Disponible)" }));
        cbxEspacio.addActionListener(this::cbxEspacioActionPerformed);

        txtFechaInicio.addActionListener(this::txtFechaInicioActionPerformed);

        txtMeses.addActionListener(this::txtMesesActionPerformed);

        btnEncola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncola.setText("Encolar Contrato");
        btnEncola.addActionListener(this::btnEncolaActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar Solicitud");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEncola, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxEspacio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEncola, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cola de Contratos Pendientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnProcesar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProcesar.setText("Procesar Siguiente Contrato (FIFO)");
        btnProcesar.addActionListener(this::btnProcesarActionPerformed);

        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Contrato", "Cliente", "Espacio", "Fecha Inicio", "Meses", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblContratos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnProcesar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnProcesar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(237, 237, 237)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncolaActionPerformed
        String inicioTexto = txtFechaInicio.getText().trim();
        String finalTexto = txtMeses.getText().trim();

    if (inicioTexto.isEmpty() || finalTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Debe completar las fechas.");
        return;
    }

    if (cbxCliente.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
        return;
    }

    if (cbxEspacio.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un espacio.");
        return;
    }

    try {

        LocalDate fechaInicio = LocalDate.parse(inicioTexto);
        LocalDate fechaFinal = LocalDate.parse(finalTexto);
        String clienteSeleccionado = cbxCliente.getSelectedItem().toString();
        String espacioSeleccionado = cbxEspacio.getSelectedItem().toString();
        String cedula = clienteSeleccionado.substring(0,clienteSeleccionado.indexOf(" - "));
        String numeroEspacio = espacioSeleccionado.substring(0, espacioSeleccionado.indexOf(" - "));

        Contrato contrato = controlador.solicitarContrato(cedula,numeroEspacio, fechaInicio, fechaFinal);

        Object[] fila = {
            contrato.getNumeroContrato(),
            contrato.getCliente().getNombreCompleto(),
            contrato.getEspacio().getNumeroEspacio(),
            contrato.getFechaInicio(),
            contrato.getFechaFinal(),
            contrato.getEstado()
        };

        modeloTabla.addRow(fila);
        JOptionPane.showMessageDialog(this,"Contrato registrado correctamente.");
        limpiarCampos();

    } catch (StorageBoxException e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Las fechas deben escribirse así: 2026-08-25");
    }
    }//GEN-LAST:event_btnEncolaActionPerformed

    private void cbxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxClienteActionPerformed

    private void cbxEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEspacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEspacioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        try {

        controlador.activarSiguienteContrato();

        cargarTablaContratos();
        cargarEspacios();

        JOptionPane.showMessageDialog(
                this,
                "Contrato activado correctamente."
        );

    } catch (StorageBoxException e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void txtMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesesActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed
    private void limpiarCampos() {
        txtFechaInicio.setText("");
        txtMeses.setText("");

        if (cbxCliente.getItemCount() > 0) {
            cbxCliente.setSelectedIndex(0);
        }

        if (cbxEspacio.getItemCount() > 0) {
            cbxEspacio.setSelectedIndex(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FrmContratos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncola;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<String> cbxEspacio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContratos;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtMeses;
    // End of variables declaration//GEN-END:variables
}
