/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.EspacioControlador;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import exepciones.StorageBoxException;
import modelo.Espacio;
import modelo.TipoEspacio;
/**
 *
 * @author matam
 */
public class FrmEspacios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEspacios.class.getName());
    private DefaultTableModel modeloTabla;
    private EspacioControlador controlador;
    
    public FrmEspacios(EspacioControlador controlador) {

        initComponents();
        this.controlador = controlador;
        configurarTabla();
        cargarTablaEspacios();
        generarMapa();
        setLocationRelativeTo(null);
    }

    public FrmEspacios() {
        initComponents();
        configurarTabla();
        generarMapa();
        setLocationRelativeTo(null);
    }
    private void configurarTabla() {

    String[] columnas = {
        "Número",
        "Tipo Espacio",
        "Tamaño",
        "Precio Base",
        "Estado Actual"
    };

    modeloTabla = new DefaultTableModel(columnas, 0) {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    tblEspacios.setModel(modeloTabla);
}
    private void cargarTablaEspacios() {

    modeloTabla.setRowCount(0);

    for (Espacio espacio : controlador.listarEspacios()) {

        String estado;

        if (espacio.isOcupado()) {
            estado = "Ocupado";
        } else {
            estado = "Disponible";
        }

        Object[] fila = {
            espacio.getNumeroEspacio(),
            espacio.getTipo(),
            espacio.getTamanioM2() + " m²",
            espacio.getPrecioMensual(),
            estado
        };

        modeloTabla.addRow(fila);
    }
}    
    private void generarMapa() {

    pnlMapaMatriz.setLayout(
            new GridLayout(4, 5, 4, 4)
    );

    pnlMapaMatriz.removeAll();

    Color verde = new Color(76, 175, 80);
    Color rojo = new Color(244, 67, 54);
    Color gris = Color.LIGHT_GRAY;

    int totalCeldas = 20;
    int espaciosRegistrados =
            modeloTabla.getRowCount();

    for (int i = 0; i < totalCeldas; i++) {

        JButton boton = new JButton();

        Color color = gris;

        String texto =
                "Espacio no registrado";

        if (i < espaciosRegistrados) {

            String numero =
                    modeloTabla.getValueAt(i, 0).toString();

            String estado =
                    modeloTabla.getValueAt(i, 4).toString();

            texto = "Espacio: "
                    + numero
                    + " ("
                    + estado
                    + ")";

            if (estado.equals("Ocupado")) {

                color = rojo;

            } else {

                color = verde;
            }
        }

        boton.setBackground(color);
        boton.setOpaque(true);
        boton.setContentAreaFilled(true);
        boton.setBorderPainted(false);
        boton.setFocusable(false);
        boton.setToolTipText(texto);

        pnlMapaMatriz.add(boton);
    }

    pnlMapaMatriz.revalidate();
    pnlMapaMatriz.repaint();
}
    private void limpiarFormulario() {

    txtNumeroEspacio.setText("");
    cbxTipoEspacio.setSelectedIndex(0);
    txtTamanio.setText("5");
    txtPrecioBase.setText("25000");

    txtBuscarEspacio.setText("");

    if (cbxFiltroEspacio.getItemCount() > 0) {
        cbxFiltroEspacio.setSelectedIndex(0);
    }

    txtNumeroEspacio.setEnabled(true);
    tblEspacios.clearSelection();

    txtNumeroEspacio.requestFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroEspacio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxTipoEspacio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        btnRegistrarEspacio = new javax.swing.JButton();
        btnCambiarEstado = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminarEspacio = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTamanio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarEspacio = new javax.swing.JTextField();
        btnBuscarEspacio = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbxFiltroEspacio = new javax.swing.JComboBox<>();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEspacios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        pnlMapaMatriz = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Gestión de Espacios");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Nuevo Espacio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Número de Espacio:");

        txtNumeroEspacio.addActionListener(this::txtNumeroEspacioActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tipo de Espacio:");

        cbxTipoEspacio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxTipoEspacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));
        cbxTipoEspacio.addActionListener(this::cbxTipoEspacioActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Precio Base Mensual:");

        txtPrecioBase.addActionListener(this::txtPrecioBaseActionPerformed);

        btnRegistrarEspacio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarEspacio.setText("Registrar Espacio");
        btnRegistrarEspacio.addActionListener(this::btnRegistrarEspacioActionPerformed);

        btnCambiarEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCambiarEstado.setText("Modificar Espacio");
        btnCambiarEstado.addActionListener(this::btnCambiarEstadoActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnEliminarEspacio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarEspacio.setText("Eliminar Espacio");
        btnEliminarEspacio.addActionListener(this::btnEliminarEspacioActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tamaño (m²):");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Buscar número:");

        btnBuscarEspacio.setText("Buscar");
        btnBuscarEspacio.addActionListener(this::btnBuscarEspacioActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Filtrar:");

        cbxFiltroEspacio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pequeño", "Mediano", "Grande", "Disponible", "Ocupado" }));
        cbxFiltroEspacio.addActionListener(this::cbxFiltroEspacioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioBase)
                                    .addComponent(cbxTipoEspacio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTamanio))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscarEspacio)
                            .addComponent(cbxFiltroEspacio, 0, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarEspacio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrarEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCambiarEstado)
                        .addGap(40, 40, 40)
                        .addComponent(btnEliminarEspacio)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuscarEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEspacio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxTipoEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbxFiltroEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarEspacio)
                    .addComponent(btnCambiarEstado)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminarEspacio))
                .addGap(22, 22, 22))
        );

        pnlTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Espacios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblEspacios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Número", "Tipo ", "Tamaño", "Precio", "Estado"
            }
        ));
        tblEspacios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEspaciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEspacios);
        if (tblEspacios.getColumnModel().getColumnCount() > 0) {
            tblEspacios.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mapa de Espacios Ocupados/Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(103, 236, 103));

        pnlMapaMatriz.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlMapaMatriz.setLayout(new java.awt.GridLayout(4, 5, 4, 4));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("Verde: Disponible");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Rojo: Ocupado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(pnlMapaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlMapaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioBaseActionPerformed
        btnRegistrarEspacio.doClick();
    }//GEN-LAST:event_txtPrecioBaseActionPerformed

    private void txtNumeroEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEspacioActionPerformed
        cbxTipoEspacio.requestFocus();
    }//GEN-LAST:event_txtNumeroEspacioActionPerformed

    private void cbxTipoEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoEspacioActionPerformed
        String tipo = cbxTipoEspacio
            .getSelectedItem()
            .toString();

    if (tipo.equals("Pequeño")) {

        txtTamanio.setText("5");
        txtPrecioBase.setText("25000");

    } else if (tipo.equals("Mediano")) {

        txtTamanio.setText("10");
        txtPrecioBase.setText("45000");

    } else if (tipo.equals("Grande")) {

        txtTamanio.setText("20");
        txtPrecioBase.setText("70000");
    }
    }//GEN-LAST:event_cbxTipoEspacioActionPerformed

    private void btnRegistrarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEspacioActionPerformed
        String numero =
            txtNumeroEspacio.getText().trim();

    String tamanioTexto =
            txtTamanio.getText().trim();

    String precioTexto =
            txtPrecioBase.getText().trim();

    if (numero.isEmpty() || tamanioTexto.isEmpty() || precioTexto.isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Debe completar todos los campos.");

        return;
    }

    if (!numero.matches("[0-9]+")) {

        JOptionPane.showMessageDialog(this,
                "El número de espacio solo puede contener números.");

        return;
    }

    try {

        double tamanio =
                Double.parseDouble(tamanioTexto);

        double precio =
                Double.parseDouble(precioTexto);

        if (tamanio <= 0 || precio <= 0) {

            JOptionPane.showMessageDialog(this,
                    "El tamaño y el precio deben ser mayores a 0.");

            return;
        }

        TipoEspacio tipo;

        String tipoSeleccionado =
                cbxTipoEspacio.getSelectedItem().toString();

        if (tipoSeleccionado.equals("Pequeño")) {

            tipo = TipoEspacio.PEQUENO;

        } else if (tipoSeleccionado.equals("Mediano")) {

            tipo = TipoEspacio.MEDIANO;

        } else {

            tipo = TipoEspacio.GRANDE;
        }

        controlador.registrarEspacio(numero, tipo, tamanio, precio);

        cargarTablaEspacios();
        generarMapa();
        limpiarFormulario();

        JOptionPane.showMessageDialog(this,
                "Espacio registrado correctamente.");

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "El tamaño y el precio deben ser números.");

    } catch (StorageBoxException e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnRegistrarEspacioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        int fila = tblEspacios.getSelectedRow();

    if (fila == -1) {

        JOptionPane.showMessageDialog(this,
                "Seleccione un espacio para modificar.");

        return;
    }

    String numero =
            modeloTabla.getValueAt(fila, 0).toString();

    String tamanioTexto =
            txtTamanio.getText().trim();

    String precioTexto =
            txtPrecioBase.getText().trim();

    if (tamanioTexto.isEmpty()
            || precioTexto.isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Debe completar todos los campos.");

        return;
    }

    try {

        double tamanio =
                Double.parseDouble(tamanioTexto);

        double precio =
                Double.parseDouble(precioTexto);

        TipoEspacio tipo;

        String tipoSeleccionado =
                cbxTipoEspacio.getSelectedItem().toString();

        if (tipoSeleccionado.equals("Pequeño")) {

            tipo = TipoEspacio.PEQUENO;

        } else if (tipoSeleccionado.equals("Mediano")) {

            tipo = TipoEspacio.MEDIANO;

        } else {

            tipo = TipoEspacio.GRANDE;
        }

        controlador.modificarEspacio(
                numero,
                tipo,
                tamanio,
                precio
        );

        cargarTablaEspacios();
        generarMapa();
        limpiarFormulario();

        JOptionPane.showMessageDialog(this,
                "Espacio modificado correctamente.");

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "El tamaño y el precio deben ser números.");

    } catch (StorageBoxException e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void btnEliminarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEspacioActionPerformed
        int fila = tblEspacios.getSelectedRow();

    if (fila == -1) {

        JOptionPane.showMessageDialog(this,
                "Seleccione un espacio para eliminar.");

        return;
    }

    String numero =
            modeloTabla.getValueAt(fila, 0).toString();

    int confirmar =
            JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar el espacio?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );

    if (confirmar == JOptionPane.YES_OPTION) {

        try {

            controlador.eliminarEspacio(numero);

            cargarTablaEspacios();
            generarMapa();
            limpiarFormulario();

            JOptionPane.showMessageDialog(this,
                    "Espacio eliminado correctamente.");

        } catch (StorageBoxException e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }
    }//GEN-LAST:event_btnEliminarEspacioActionPerformed

    private void tblEspaciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEspaciosMouseClicked
        int fila = tblEspacios.getSelectedRow();

    if (fila != -1) {

        txtNumeroEspacio.setText(
                modeloTabla.getValueAt(fila, 0).toString()
        );

        String tipo =
                modeloTabla.getValueAt(fila, 1).toString();

        if (tipo.equals("Pequeño")) {

            cbxTipoEspacio.setSelectedItem("Pequeño");

        } else if (tipo.equals("Mediano")) {

            cbxTipoEspacio.setSelectedItem("Mediano");

        } else {

            cbxTipoEspacio.setSelectedItem("Grande");
        }

        String tamanio =
                modeloTabla.getValueAt(fila, 2).toString();

        tamanio = tamanio.replace(" m²", "");

        txtTamanio.setText(tamanio);

        txtPrecioBase.setText(
                modeloTabla.getValueAt(fila, 3).toString()
        );

        txtNumeroEspacio.setEnabled(false);
    }
    }//GEN-LAST:event_tblEspaciosMouseClicked

    private void btnBuscarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEspacioActionPerformed
        String numero = txtBuscarEspacio.getText().trim();

    if (numero.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Ingrese el número del espacio.");
        return;
    }

    if (!numero.matches("[0-9]+")) {
        JOptionPane.showMessageDialog(this,
                "El número de espacio solo puede contener números.");
        return;
    }

    Espacio espacio = controlador.buscarEspacio(numero);

    if (espacio == null) {
        JOptionPane.showMessageDialog(this,
                "No se encontró el espacio.");
        return;
    }

    cargarTablaEspacios();

    for (int i = 0; i < modeloTabla.getRowCount(); i++) {

        if (modeloTabla.getValueAt(i, 0).toString().equals(numero)) {

            tblEspacios.setRowSelectionInterval(i, i);

            txtNumeroEspacio.setText(
                    modeloTabla.getValueAt(i, 0).toString()
            );

            String tipo =
                    modeloTabla.getValueAt(i, 1).toString();

            cbxTipoEspacio.setSelectedItem(tipo);

            String tamanio =
                    modeloTabla.getValueAt(i, 2).toString();

            tamanio = tamanio.replace(" m²", "");

            txtTamanio.setText(tamanio);

            txtPrecioBase.setText(
                    modeloTabla.getValueAt(i, 3).toString()
            );

            txtNumeroEspacio.setEnabled(false);

            break;
        }
    }
    }//GEN-LAST:event_btnBuscarEspacioActionPerformed

    private void cbxFiltroEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFiltroEspacioActionPerformed
        if (controlador == null || modeloTabla == null) {
        return;
    }

    String filtro =
            cbxFiltroEspacio.getSelectedItem().toString();

    modeloTabla.setRowCount(0);

    for (Espacio espacio : controlador.filtrarEspacios(filtro)) {

        String estado;

        if (espacio.isOcupado()) {
            estado = "Ocupado";
        } else {
            estado = "Disponible";
        }

        boolean mostrar = false;

        if (filtro.equals("Todos")) {

            mostrar = true;

        } else if (filtro.equals("Pequeño")
                && espacio.getTipo() == TipoEspacio.PEQUENO) {

            mostrar = true;

        } else if (filtro.equals("Mediano")
                && espacio.getTipo() == TipoEspacio.MEDIANO) {

            mostrar = true;

        } else if (filtro.equals("Grande")
                && espacio.getTipo() == TipoEspacio.GRANDE) {

            mostrar = true;

        } else if (filtro.equals("Disponible")
                && !espacio.isOcupado()) {

            mostrar = true;

        } else if (filtro.equals("Ocupado")
                && espacio.isOcupado()) {

            mostrar = true;
        }

        if (mostrar) {

            Object[] fila = {
                espacio.getNumeroEspacio(),
                espacio.getTipo(),
                espacio.getTamanioM2() + " m²",
                espacio.getPrecioMensual(),
                estado
            };

            modeloTabla.addRow(fila);
        }
    }
    }//GEN-LAST:event_cbxFiltroEspacioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmEspacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FrmEspacios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEspacio;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnEliminarEspacio;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarEspacio;
    private javax.swing.JComboBox<String> cbxFiltroEspacio;
    private javax.swing.JComboBox<String> cbxTipoEspacio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlMapaMatriz;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JTable tblEspacios;
    private javax.swing.JTextField txtBuscarEspacio;
    private javax.swing.JTextField txtNumeroEspacio;
    private javax.swing.JTextField txtPrecioBase;
    private javax.swing.JTextField txtTamanio;
    // End of variables declaration//GEN-END:variables
}
